### ISSUE TITLE
SFCCONSOLE visual class lib and sfctrls.h missing

### ISSUE THREAD

**Issue by ghost** [VFPX/OOPMenu#1]
Hello!
Thanks for the project! It's really very impressive.
Can you please upload the two missing files?

**Comment by DougHennig** [comment]
I added SFCtrls.h and removed the classes that used SFConsole since they aren't used.

**Comment by ghost** [comment]
Thanks, Doug!
Let me ask You one more question: is there a way to use the library for implementing a conext menu instead of DEFINE POPUP?

**Comment by DougHennig** [comment]
See the documentation for the SFShortcutMenu class.

**Comment by ghost** [comment]
Thank You, Doug!
