### ISSUE TITLE
Pad Invisible but is visible

### ISSUE THREAD

**Issue by creacionesintegrales** [VFPX/OOPMenu#10]
## 📝 Provide detailed reproduction steps (if any)

1. AddPad with option lVisible=.f.
2. Show menu
3. Pad is visible

### ✔️ Expected result

_What is the expected result of the above steps?_
Pad invisible
### ❌ Actual result

_What is the actual result of the above steps?_
Pad visible
## 📷 Screenshots
![image](https://user-images.githubusercontent.com/71299475/220501215-1ed63b44-68c9-4525-8a54-9d477901c52d.png)
![image](https://user-images.githubusercontent.com/71299475/220501267-adce7b66-b734-4afe-9568-2d2f1715ea70.png)

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_
[falla.zip](https://github.com/VFPX/OOPMenu/files/10799330/falla.zip)

From the command window run

do menudin with 35

**Comment by creacionesintegrales** [comment]
One thing I notice is that if I do oMenu.Show() do oMenu.Pad07.Hide() the pad hide but But if I do instead oMenu.Pad07.lVisible=.f. nothing happens. And if once it’s hidden I do it again oMenu.Show() the pad is visible again.
That is to say that the Show method is not taking into account as it defines the property lVisible

**Comment by creacionesintegrales** [comment]
I will add a property (lLock) to prevent lVisible from being changed with a normal Show and I will add a forced parameter to both Show and Hide so that only the lVisible can be changed.

**Comment by creacionesintegrales** [comment]
Simplify the question and solve it as follows.

1. Add the lAllow property to the sfpad and sfbar objects
2. In the methods Show, Hide and Assign_lVisible I act if lAllow is in true.

The lAllow property charges you at startup And it is for a security issue since not all configurations allow you to use all options

**Comment by DougHennig** [comment]
Fixed in the latest build. I simply made SFPad.Show check if lVisible is .T.
