### ISSUE TITLE
Problem with addseparatorbar

### ISSUE THREAD

**Issue by CHamlinPNP** [VFPX/OOPMenu#11]
## 📝 Provide detailed reproduction steps (if any)

1. …Call AddSeparatorBar() then executes the line
2. …loBar  = .AddBar('SFSeparatorBar', 'SFMenu.vcx', lcName) then executes the line
3. …loBar = createobject(lcClass, lnBarNumber, .cPopupName, lcName, llSpecified)

I have included the code for the menu within demo.zip. 
This is using SFMenu version 2023.02.22
This particular case is it being used with VFP Advanced 10.01 Build 2404

### ✔️ Expected result

Expected it to create a separator bar given the name specified in step 2

### ❌ Actual result

What happens that an error occurs that no parameter statement was found

## 📷 Screenshots

![image](https://github.com/VFPX/OOPMenu/assets/34104227/9e28af3c-6ef5-4aca-8f81-3d1b122d4af8)
[demo.zip](https://github.com/VFPX/OOPMenu/files/15276890/demo.zip)

**Comment by DougHennig** [comment]
Your demo program works for me. The parent class of SFSeparatorBar does have a PARAMETER statement. Check that you didn't inadvertently add some code to SFSeparatorBar.Init,

**Comment by CHamlinPNP** [comment]
I believe I found the issue. I have a class sfseparatorbar within sfctrls which it is conflicting with.

**Comment by CHamlinPNP** [comment]
Found it. List Manager uses sfseparatorbar that is defined as a separator in sfctrls.vcx of List Manager
In the same class library...sfctrls.vcx for the List Manager has another definition of sfseparatorbar as sfcontainer.

It is due to this conflict that it is having issues.

**Comment by DougHennig** [comment]
You can remove SFSeparatorBar in SFCtrls.vcx. It isn't used anywhere.
