### ISSUE TITLE
Refreshing a menu makes a modal form modeless

### ISSUE THREAD

**Issue by atlopes** [VFPX/OOPMenu#2]
Doug

If a menu is refreshed while a modal form is shown, the menu items become available according to their SkipFor expression regardless of the form's WindowType.

To reproduce:

1. Show a modal form.
2. Menu items are normally disabled.
3. Refresh the menu while the form is active.
4. Menu items are enabled (or not) according to the conditions of their SkipFor expressions.

Visually:

Points 1. and 2.
![Points 1. and 2.](https://user-images.githubusercontent.com/27675705/124365718-a9854300-dc41-11eb-853a-2bf88e366a61.png)

Points 3. and 4.
![Points 3. and 4.](https://user-images.githubusercontent.com/27675705/124365730-c15cc700-dc41-11eb-83f4-ce08e8770df1.png)

Is there a way for the menu to be refreshed and respect the modality of the active form?

**Comment by DougHennig** [comment]
I believe that is the normal behavior of menus (it is a trick VFP developers use to enable menu items for modal forms). The only solution is to add SKIP FOR conditions that disable the items or to not refresh the menu when the modal form is displayed.

**Comment by atlopes** [comment]
Thank you, Doug. I'll have to find a way to overcome this problem, then.

The problem popped up while testing a DPI-aware application: when the user changes the text scale, the system menu's font size must change also.

Without a refresh, the change in the menu will not be visible. But refreshing it introduces this undesirable side-effect.
