### ISSUE TITLE
Setup/CleanUp code is currently not dealt with during ConvertMNX process

### ISSUE THREAD

**Issue by CHamlinPNP** [VFPX/OOPMenu#3]
## 📝 Provide a description of the new feature

If you are going to be able to process an existing menu...then it also needs to be able to deal with the Setup and CleanUp code within the menu file.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by DougHennig** [comment]
The comments in ConvertMNX.prg indicate that it's incomplete, including not handling Setup and Cleanup code. However, if you attach the MNX and MNT files of a menu you want to convert here, I'll look into it.

**Comment by CHamlinPNP** [comment]
Here you go

[OOPMenu.zip](https://github.com/VFPX/OOPMenu/files/8696085/OOPMenu.zip)

**Comment by DougHennig** [comment]
This is taken care of in the latest release. Note that you now have to pass the name of the PRG you're generating to the GenerateMenu method:

loGenerator.GenerateMenu(loMenu, 'menu.prg')
