### ISSUE TITLE
Single menu items not converted

### ISSUE THREAD

**Issue by CHamlinPNP** [VFPX/OOPMenu#4]
## 📝 Provide detailed reproduction steps (if any)

1. …Using ConvertMNX to convert existing MNX
2. …Have a menu such as:
DEFINE PAD _6c014sf00 OF _MSYSMENU PROMPT "\<Quit" COLOR SCHEME 3 KEY ALT+Q, ""
ON SELECTION PAD _6c014sf00 OF _MSYSMENU DO quitmnu
3. …The above pad does not appear in the converted code

### ✔️ Expected result

I expected to see all of the menu items, but am finding...like explained above...some items are not converted properly.

### ❌ Actual result

_What is the actual result of the above steps?_

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by DougHennig** [comment]
Please attach the MNX and MNT files of a menu with this issue.

**Comment by CHamlinPNP** [comment]
Here you go

[OOPMenu.zip](https://github.com/VFPX/OOPMenu/files/8696083/OOPMenu.zip)

**Comment by CHamlinPNP** [comment]
There is a bigger example with the same menu...the reports menu pad (analyticsr).

Original menu has the following entries:

![image](https://user-images.githubusercontent.com/34104227/168631817-ab8e720c-31e8-43bf-b820-4bbeb4a92cda.png)

But when converted it turns into:

![image](https://user-images.githubusercontent.com/34104227/168632049-ddc0fa09-da6b-4f2c-b0f3-c76bd8446da8.png)

and the actual classes show:

![image](https://user-images.githubusercontent.com/34104227/168632237-0409cd89-7f43-4fb3-9b70-367d837140e1.png)

**Comment by DougHennig** [comment]
This is fixed in the latest release.
