### ISSUE TITLE
Problem with separator bar in original MNX

### ISSUE THREAD

**Issue by CHamlinPNP** [VFPX/OOPMenu#5]
## 📝 Provide detailed reproduction steps (if any)

1. …Another issue with the ConvertMNX routine. It properly recognized that the original code had DEFINE BAR 7 OF discharges PROMPT "\-"
2. …It did add a call such as....AddSeparatorBar()
3. …Problem is...it also created an empty
*===============================================================================
Define Class _20d0ycchp As SFBar Of SFMenu.vcx
*===============================================================================

EndDefine
4. ...It properly never referenced this bar...it converted the next bar, but missed the last bar altogether. It was like the separator bar through off what it is doing.

### ✔️ Expected result

Deal with each menu item of the original menu

### ❌ Actual result

screen shots show original menu as an .MPR representation
2nd shot shows the conversion of the pad
3rd shot shows what it did with the bars on the pad

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_
![image](https://user-images.githubusercontent.com/34104227/168452571-e43bed23-881e-49e9-acc2-8ea1ba7a1248.png)
![image](https://user-images.githubusercontent.com/34104227/168452590-c4f42b82-f7ba-4d4d-9fa6-5abc7e1e60b1.png)
![image](https://user-images.githubusercontent.com/34104227/168452600-016491a9-a504-4bf3-8ac5-dc45a06d2336.png)

**Comment by DougHennig** [comment]
Please attach the MNX and MNT files of a menu with this issue.

**Comment by CHamlinPNP** [comment]
Here are the files requested.

[OOPMenu.zip](https://github.com/VFPX/OOPMenu/files/8696082/OOPMenu.zip)

**Comment by DougHennig** [comment]
The separator bar in the Discharges pad is defined as a submenu rather than a command, which confuses the converter. The record in the MNX file following the separator is an submenu definition, so the conversion process is doing what it's supposed to. Fix your menu so all of the separators are commands instead and they'll be handled properly.

**Comment by CHamlinPNP** [comment]
BUT standard VFP ... a separator bar is just that...just a bar to separate your menu. Because it starts with a \ it is actually a disabled item. There would never be any code or anything. The conversion routine should just have this exception added to it...a separator bar is just that and nothing else. 

If you did add code to a separator bar...I have no idea how you would ever get it to execute...that is really not even a possibility is it?

**Comment by DougHennig** [comment]
If you open the MNX file as a table and browse it, you'll find the record following the separator bar defines a submenu that's empty. Yes, I could spend some time figuring out how to ignore that record, but I'm not going to, so you can either implement that yourself or simply edit the menu as I suggested.

**Comment by DougHennig** [comment]
Just to be clear, I'm not suggested you specify a command for the separator bar, just change the type to Command (which makes more sense than Submenu anyway and will work better for conversion).

**Comment by CHamlinPNP** [comment]
I understand what you are saying...but I have to respectfully disagree with you. VFP by default when inserting a bar...it defaults to submenu. Since we are just creating a separator bar...then I assume I am far from the only one who has just left it alone since it is ignored anyways.

![image](https://user-images.githubusercontent.com/34104227/168851627-bf380167-5311-46ea-9c77-e6de91a90eeb.png)

**Comment by DougHennig** [comment]
OK, you convinced me :) -- it's fixed.
