### ISSUE TITLE
SeparatorBar issue

### ISSUE THREAD

**Issue by CHamlinPNP** [VFPX/OOPMenu#6]
## 📝 Provide detailed reproduction steps (if any)

1. …Problem arises during the initial SHOW of the menu
2. …It then is running the code for the show and during that process if it hits a separatorbar
3. …it receives an error...see below

### ✔️ Expected result

I would expect it to just put in a separator bar and not try to have any subbars or anything

### ❌ Actual result

Actual result is that the property COUNT does not exist for separator bars

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/34104227/169176147-5c07984c-501d-414d-ad61-7db485058e60.png)

![image](https://user-images.githubusercontent.com/34104227/169176777-47a0bdda-b790-43e1-8e89-f74a65fd9f12.png)

**Comment by DougHennig** [comment]
I can't reproduce that: I used the PRG generated from your rms.mnx (removing the cSkipFor lines because they won't work for me) and it works correctly:

![image](https://user-images.githubusercontent.com/12052409/169341573-0745fe3a-aa23-4a6e-8d8c-9a2b8ea7746e.png)

**Comment by CHamlinPNP** [comment]
But it happens everytime for me. If a Separatorbar does not have the property of County...then how does yours NOT get an error when going through this code? Does not make sense to me.

**Comment by DougHennig** [comment]
SFSeparatorBar is a subclass of SFBar, and its BaseClass is Collection, so it does have a Count property:

![image](https://user-images.githubusercontent.com/12052409/169831889-d4d195d5-b0fe-494f-98c5-5971aac3c83a.png)

**Comment by CHamlinPNP** [comment]
I believe it was a problem with my subclass collection class that caused this issue.
