### ISSUE TITLE
Pad with no submenu

### ISSUE THREAD

**Issue by CHamlinPNP** [VFPX/OOPMenu#7]
## 📝 Provide detailed reproduction steps (if any)

1. … I have a menu which has the description of:
              this.AddPad("quitmenu", '', "quitmenu")
2. … The code for the "quitmenu" class is:
		*===============================================================================
		Define Class quitmenu as SFPad of SFMenu.vcx
		*===============================================================================
			cCaption = [\<Quit]
			cPadPosition = [after modules]
			cPopupName = [quitmenu]
			cOnClickCommand = [DO quitmnu]
		enddefine
3. … When clicking the pad it does not execute the value of "cOnClickCommand"

### ✔️ Expected result

The expected result would be that when the pad is clicked that it would fire the cOnClickCommand and in this particular case exit my system.

### ❌ Actual result

What actually happens is that it does absolutely nothing. No errors, no messages, nothing...it acts like the pad is not clicked.

## 📷 Screenshots

https://user-images.githubusercontent.com/34104227/176696082-31f1b685-e814-4d79-8585-4e6c53e00d55.mp4

**Comment by DougHennig** [comment]
As the documentation (https://github.com/VFPX/OOPMenu/blob/master/Documentation/Overview.md) notes, you have to use SFPadCommand.
