### ISSUE TITLE
How to add controls to the menu?

### ISSUE THREAD

**Issue by creacionesintegrales** [VFPX/OOPMenu#8]
I see there is a class called sfctrls.
Can I add controls to my menu?
Could you give me an example?

**Comment by DougHennig** [comment]
This project is just a wrapper for the VFP menu system so you cannot add controls other than menu bars to the menu.

**Comment by creacionesintegrales** [comment]
Ok, but VFP menu support font and colors. Could you tell me how I perform that task with the object.

**Comment by DougHennig** [comment]
I chose not to support fonts and colors because those normally are not used in standard Windows applications. Feel free to add support for that if you wish.
