### ISSUE TITLE
Menu has not been defined with DEFINE POPUP (Error 165) when any ancestor not is visible

### ISSUE THREAD

**Issue by creacionesintegrales** [VFPX/OOPMenu#9]
## 📝 Provide detailed reproduction steps (if any)

1. …Create popup invisible
2. …Create bar into popup
3. …Whe menu show Error

### ✔️ Expected result

_What is the expected result of the above steps?_

Show objects visibles and hide objects not visibles

### ❌ Actual result

_What is the actual result of the above steps?_

No create menu

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

![image](https://user-images.githubusercontent.com/71299475/220132262-715f6192-d128-4d18-a2e6-49c3c5e900ff.png)

**Comment by DougHennig** [comment]
Please provide some code to reproduce this.

**Comment by creacionesintegrales** [comment]
I give you the full example that I arm. The example arm a 100% dynamic menu using the class.
[falla.zip](https://github.com/VFPX/OOPMenu/files/10788008/falla.zip)

From the command window make a default set to the folder where the programs are.

For example, SET DEFAULT TO d:\pruebas\oopmenu-master\falla\

Then,

DO menudin WITH 35

That 35 has to do with the configuration code that you must use to assemble the menu.

You will see that there are about 33 different configurations.

Thanks.

Francisco Prieto
Capilla del Monte
Córdoba
Argentina

**Comment by DougHennig** [comment]
Thank you--that helped me track it down. This is fixed in the latest build.
